ExcitedStates/qfit-3.0

qfit/get_metrics.py

Prevented get_metrics from outputting RMSF for waters.

Adjusted get_metrics script to normalize RMSF between conformers.

---

README.md
qfit/b_factor.py
qfit/find_altlocs_near_ligand.py
qfit/qfit_RMSF.py
scripts/check_qfit_run.sh
scripts/post_refine_phenix.sh

removing a bunch of unneeded inputs and outputs.

Updating bfactor, find_alt_loc, qfitRMSF

---

qfit/qfit.py
qfit/qfit_covalent_ligand.py
qfit/qfit_protein.py
qfit/qfit_residue.py

1. Rename dofs-stepsize to dihedral-stepsize (from what I can tell, this is what this parameter actually controls)
1. Make `qfit_protein --help` print the default settings.

rename dofs-stepsize → dihedral-stepsize; qfit_protein: cleanup help

---

qfit/qfit_protein.py
qfit/subset_structure_AH.py

This was merged to dev in b92545d, and should have been pushed to master at the same time.

Fix causes of IndentationError

---

src/qfit/qfit_ligand.py

Fix typo that causes qfit_ligand to crash

---

.gitignore
src/qfit/qfit.py
src/qfit/qfit_protein.py
src/qfit/validator.py

I cleaned up some minor things in the code, including some variable naming and comments text, and simplified an area with duplicated code.

Minor tweaks to for code readability

---

src/qfit/logtools.py
src/qfit/qfit.py
src/qfit/qfit_protein.py
src/qfit/relabel.py
src/qfit/samplers.py
src/qfit/spacegroups.py
src/qfit/structure/residue.py

What it says on the tin.
Most of these commits won't change much.

Add some comments, logs, and improve messages

---

src/qfit/qfit.py
src/qfit/qfit_ligand.py
src/qfit/samplers.py
tests/test_qfit_ligand.py

bug in samplers script (local search tool).

Fixing bug in np multiplication in local search function used in qfit ligand. Minor typos in qfit ligand to make it run/catch errors

---

scripts/post_refine_phenix.sh

Main discussion on N/Q/H flips in the commit message for 8f15653 .

Changes to refinement procedure (NQH flips, real-space refinement too!)

---

README.md

Removed section label syntax not supported by GitHub Flavored Markdown

Fixed README syntax error

---

src/qfit/qfit.py

Typo in line 756:  if self.options.write_intermediate_conformers:

Fix typo in write_intermediate_conformers

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md
CONTRIBUTING.md

Here's some guidelines for what we would like contributors to do.
It can be expanded on / improved as we go.

Add contributor guides

---

pyproject.toml
setup.py
src/qfit/qfit.py
src/qfit/qfit_ligand.py
src/qfit/qfit_protein.py
src/qfit/qfit_residue.py
src/qfit/relabel.py

----
Reviewer suggested that we should think about reproducibility.
Entropy is introduced into the output in many places through np.random.
In this PR, we replace calls to np.random.* with a np.random.default_rng() that gets initialised with a user-provided seed value.
- Add --random-seed to provide option for reproducible runs
----

Add --random-seed to provide option for reproducible runs

---

src/qfit/qfit_residue.py

Changing --write-intermediate-conformers  to --write_intermediate_conformers so that qFit protein and qFit residue match. 
----
----

Changing write-intermediate-conformers argument to match qfit_protein

---

README.md
example/apoF_chainA.pdb

PDB: 7A4M; ApoFerritin Chain A
----
----

Added cryo-EM and qFit ligand examples

---

environment.yml
scripts/post/alpha_rmsd.py
scripts/post/b_factor.py
scripts/post/compare_apo_holo.py
scripts/post/find_altlocs_near_ligand.py
scripts/post/find_largest_ligand.py
scripts/post/get_lig_chain_res.py
scripts/post/get_metrics.py
scripts/post/lig_occ.py
scripts/post/qfit_RMSF.py
scripts/post/qfit_final_refine_cryoem.sh
scripts/post/qfit_final_refine_xray.sh
scripts/post/relabel_chain.py
scripts/post/reorder_pdb.py
scripts/post/subset_structure_AH.py
scripts/post/water_clash.py
scripts/post/water_stats.py
setup.py

----
This pull request will introduce a bunch of new analysis scripts and updates existing analysis scripts.

adding new post qfit analysis scripts

---

README.md

Fixing a typo in the line directing refinement from a cryoEM/ccp4 based structure. 
----
----

correcting line for post qFit refine cryoEM

---

src/qfit/qfit_protein.py
src/qfit/structure/base_structure.py
src/qfit/structure/pdbfile.py
src/qfit/structure/structure.py

adding qfit_protein for scale/cryst

---

.github/workflows/main.yml

----
There was a reference to the 'master' branch in the CI yml file.
This now refers to 'main'.
- Renamed 'master' branch to 'main'
----

Fix CI after master-to-main switch

---

src/qfit/redistribute_cull_low_occupancies.py

This pull request will update the redistribute occ script which is use in the post-qFit refinement script.
1) It will removed hydrogens that are labeled with their own altloc, require them to be full occupancy and remove the label.
2) It will require on an atom by atom basis for all occupancies to add up to 1 for protein atoms. 
----
----

Update redistribute occ: remove trailing H & norm occ

---

README.md
scripts/post/qfit_final_refine_xray.sh

----
- post_refine: Add hydrogen using ready_set & create ligand cif file there
- post_refine: Do NQH flips within refinement loop as molprobity often crashes
- Changes to post_qfit_phenix_refine.sh protocol
- Now using Phenix 1.20
----

a post refine script that works!

---

README.md

----
The README is updated to show instructions for how to handle conda on M1 Macs.
`mkl` will never be updated for arm processors, and whether CPLEX will be updated for arm64 processors in the `ibmdecisionoptimization` conda repo is anyone's guess.
In light of that, this is a good solution.
Will close #172 .
N/A
----

Improve README for M1 Macs

---

src/qfit/qfit.py

----
- Clarified warning about AttributeError (partially addresses #141 )
----

Clarify warning about AttributeError at Cβ

---

src/qfit/qfit.py

----
In PR #185 , via 2806cdff, I introduced bug #190 .
Turns out there were more places that relied on self.options.directory
being mutated to get the correct directory.
I've updated this with a directory_name in a _BaseQFit job, as well as
an overriding method in QFitRotamericResidue.
This closes #190 .
N/A
I caused this bug before the last release. Since this is caught between releases, we don't need a release note.
----

Fix multiconformer_model.pdb not found error when it is actually present

---

scripts/post/calc_OP.py

print lines and unnecessary/inaccurate comments
----
----

removing lines

---

README.md

----
If we switch the base branch of this repo to `dev`, it will make the PR process a bit easier for devs.
Unfortunately, the default branch that will be cloned by a user (if they don't specify a branch to grab in the `git clone`) will be `dev`.
This amends the installation notes to make sure users grab the `main` branch.
N/A

Instruct users to install qFit from main branch code

---

scripts/post/qfit_final_refine_xray.sh

Since phenix changed them again!!
----
This is a quick fix to change an output name of a PDB file since PHENIX CHANGED HOW IT NAMES THINGS AGAIN!!
Also, explicitly stating riding hydrogens for the last two refinement cycles.

Refine script: output names and riding hydrogens

---

src/qfit/redistribute_cull_low_occupancies.py

----
Fixing break versus blank return statement.

fixing typo in redistribute_cull_low_occupancies.py

---

src/qfit/qfit_residue.py

----
type='str' was duplicated in the args part of qfit_residue, therefore removing.

removing duplicate str statement

---

src/qfit/qfit_residue.py

commented out qfit.write_maps and tested on 1gwe

---

.devcontainer/Dockerfile
.devcontainer/requirements.develop.txt

----
The devcontainer broke when I upgraded to an M1 Mac (CPLEX not available on ARM processors).
This PR fixes the devcontainer.
For bonus info, this is a VSCode integration to unify developer environments, etc.
N/A
----

Repair vscode devcontainer

---

src/qfit/qfit_residue.py

This function is not necessary and prevents qFit residue from running
----
----

remove second line of write maps

---

src/qfit/qfit.py

This is deleted commented code (commented for 4+ years). It is related to scaling in qFit transformer function, which is now done within the transformer function
----
This PR is deleted code that has been commented out for 4+ years. It is all duplicates from other places in the code (new functions or right below the commented code).

Cleaning out old commented code

---

src/qfit/utils/normalize_to_precision.py

----
changing name of array to reflect that we normalize outside of this funciton

change normalized_arr to arr

---

src/qfit/qfit.py

B-factors are not culled when qFit downsamples due to large number of combinations, throwing and error and removing residues from output file.  moving Jonathan's fix over to the blacken dev branch to prevent me from dealing with many merge issues.
----
----

fixing b-factor culling error

---

src/qfit/qfit.py

This was left in here after trying to get the sum(occ)=1 in MIQP. It is no longer needed and is throwing an error.
----
----

removing ligand specifying line in MIQP

---

src/qfit/qfit.py

change rmsd cutoff in qFit segment

---

scripts/post/qfit_final_refine_xray.sh

As we check for rotamer for NQH residues in qFit, it is less likely we need to optimize their positions during refinement. Reduce takes an enormous amount of memory, causing refinement to crash. This change will allow the refinement to run without checking for these flips and tell the user if it has run refinement without checking for these flips.
----
----

adding reduce failure flag

---

scripts/post/qfit_final_refine_xray.sh

----
Turning off NQH filps and move around ligand names
----

more refinement errors

---

src/qfit/qfit.py
src/qfit/structure/structure.py

----
This PR is fixing the defunt normalize occupancy script. It re-writes it so it actually works.
And it overcomes stupid float number issues in python.

normalize occupancy re-implementation

---

scripts/post/b_factor.py
src/qfit/structure/structure.py

clean up code

---

scripts/post/qfit_final_refine_xray.sh

----
adding in 
optimize_xyz_weight and optimize_adp_weight to final refinement
----

adding target weight params to final refine

---

src/qfit/qfit_protein.py

----
This is creating a flag in qFit protein that changes OXT names to O to reduce issue within the qFit code.

updating OXT issues

---

README.md
scripts/post/qfit_RMSF.py
src/qfit/qfit.py
src/qfit/qfit_protein.py

write intermediate conformers does not match what is in the rest of the code
----
This is fixing the input argument of write_intermediate_conformers to match the rest of the code.

updating write intermediate conformers argument

---

README.md

update refinement protocol

---

setup.py
src/qfit/create_rot_lib.py

updating function for rotamer to not miss chi 1!

---

src/qfit/qfit_ligand.py
tests/test_qfit_ligand.py

- [] Fill out the template below.
----
The new changes will allow qFit-ligand script to output a ligand inserted PDB model 
We must be able to understand the purpose of your change from this description. If we can't get a good idea of the benefits of the change from the description here, the pull request may be closed at the maintainers' discretion.

Output ligand inserted in pdb

---

README.md

----
Updating to work on M1 Mac. Also works on linux
----

updating numpy and python versions to work on M1 Macs

---

.github/workflows/main.yml
environment.yml
pyproject.toml
setup.py

----
This is an addition to PR #356, which fixed the python, numpy, and pandas version in the Readme but not in the tests. This now only tests Python 3.9 and has the same packages as the Readme. It also removes the 1.4 cap on Pandas. It's unclear why that was originally put there. 
We also remove 
----

Updating python, numpy, pandas versions within tests

---

README.md
scripts/post/find_close_residues.py
scripts/post/subset_structure_AH.py

Edit post qFit analysis scripts

---

README.md

----
Adding most recent paper to readme

Update README.md to include most recent paper

---

src/qfit/qfit.py
src/qfit/qfit_protein.py

----
Correcting so crystal and scale info are now output into multiconformer_model2.pdb

Correct crystal and scale info

---

src/qfit/qfit.py

This is removing the option to run phenix.refinement on individual residues within the residue portion of qFit. This code block was always False and there was no ability to turn it on to True wit qFit protein or ligand.
Unless phenix becomes more stable with their variable names, I suggest not re-implementing this with Phenix.
Note from Daniel Keedy on the job of this block of code:
'It is subtly different from just refinement with all anisotropic B’s, b/c the single residue …

Removing the Phenix Aniso refinement option

---

src/qfit/qfit.py

----
We currently sample isotropic backbone by following cartesian directions. This pull request would change the sampling in the direction of Cβ-Cα, C-N, and (Cβ-Cα × C-N). These new directions are not quite the same as a backrub motion, but this opens the door for future implementations where we might more directly address those cases.    
Change isotropic backbone sampling direction.
----

change isotropic sampling directions in backbone

---

src/qfit/qfit_protein.py

change line 680 from multiconformer_model.tofile() to multiconformer.tofile()
----
quick fix in _run_qfit_segment, change line 680 from multiconformer_model.tofile() to multiconformer.tofile()
----

Updating output multiconformer due to typo

---

scripts/post/lig_occ.py

----
Adding B-factor info to ligand occupancy script

Updating Ligand Occupany script to extract average b-factor

---

scripts/post/calc_rscc.py

Adding post analysis script to calculate RSCC for ligand or any residue based on residue ID and chain ID
----
----

Add rscc script

---

setup.py

add get_lig_chain_res.py to setup.py

---

src/qfit/qfit_protein.py

Adding Hetatms in output of multiconformer_model2

---

src/qfit/solvers.py

Added 2 more try/except around miqp solvers to catch non-convex solutions.
----
Solver errors were not always propagating if miqp failed for non-convex solutions. This adds in additional catches

Solver Error Catches

---

setup.py

add find_close_residues.py to setup.py

---

src/qfit/qfit_ligand.py

change (mi)qp_solver_choice to (mi)qp_solver in arguments section
----
change (mi)qp_solver_choice to (mi)qp_solver in arguments of qfit_ligand.py
quick fix to qfit_ligand.py
----

fix argparse error in qfit_ligand.py

---

README.md
scripts/post/README.md
setup.py

----
1) Replacing Saulo's email with Stephanie's for main contact.
2) Adding information on -p flag on main readme

Add p flag

---

README.md
example/README.md

Add em to README.md example

---

README.md

re-implementing conda & M1 instructions

---

setup.py

Add calc rscc to setup.py

---

src/qfit/qfit_protein.py

Default labels should be those in composite omit maps
----
----

update default labels

---

src/qfit/qfit.py
src/qfit/solvers.py

----
Split QP problems over with over 3000 variables into subproblems, then merge the results.
----

split QP into 3000 conformers

---

scripts/post/qfit_final_refine_cryoem.sh

1) Ask user to put in resolution
2) only do occupancy refinement
3) updated Phenix version to deal with map-model match issue 4) remove adding hydrogens automatically
----
----

re-write em refinement

---

README.md

----
env.yml already existed. Changed Readme to reflect it.

install using enviornment.yml

---

src/qfit/structure/residue.py

----
The complete residue function (rebuild part of the residue if it is not modeled) was not working, causing issue with @natechols CCTBX conversion.  This PR fixes this function!

Fix Complete Residue

---

README.md

update order of readme

---

.github/workflows/main.yml

set ci to use macos-13

---

README.md

typo in yml file name

---

src/qfit/qfit.py
src/qfit/qfit_ligand.py

----
First change was to parallelize the ligand sampling code. All sampling functions now run simultaneously. Second change was adding a --cryo_em option to qfit_ligand.py arguments. 
Parallelize the ligand sampling and add cryo em option to qfit_ligand.py
----

Parallel ligand

---

src/qfit/qfit.py

There was a joint function only used in one spot, but is still confusing with how variable are moved around.
----
----

remove _solve_qp_and_update_conformers

---

scripts/post/create_restraints_file.py
scripts/post/qfit_final_refine_xray.sh
setup.py
src/qfit/command_line/qfit_protein.py
src/qfit/xtal/transformer.py

This PR moves around where the creation of the grouped refinement file is made - as we only use it during our second set of refinement, sometimes some conformers are collapsed or removed during the coordinate only refinement.
This pulls the function from qFit protein and now uses it as a standalone function within scripts/post and changes the x-ray refinement file.

Refinement changes

---

src/qfit/qfit.py

Too much confusion over the WARNING of too many conformers - removing this as it is causing lots of confusion
----

removing WARNING

---

README.md

formatting README

---

src/qfit/qfit.py

----
modify the _zero_out_most_similar_conformer() function to add the optional ability to add the occupancy of the conformer that gets removed to the conformer that is kept. Update the ligand RMSD check after MIQP to use this function -- ie if any conformers passing MIQP are too close together (by RMSD), remove the conf with lower occupancy and add that occupancy to the remaining conf
update ligand RMSD check to add the occupancy of the removed conformer to the one that is …

Edit _zero_out_most_similar_conformer() to add the optional ability to add the occupancy of the conformer

---

scripts/post/qfit_final_refine_ligand.sh
src/qfit/redistribute_cull_low_occupancies.py

update ligand refine to remove low occ conformers

---

README.md
example/README.md

correct comp omit for ligand

---

src/qfit/structure/residue.py

This is fixing a numpy error in the theta options line in calc_coordinates function. 
----
----

fix calc_coord function

---

README.md
environment.yml

476 switch conda to mamba and enforce conda forge

---

scripts/post/qfit_final_refine_xray.sh

Updating the syntax for label names in refinement
----
----

update input label names

---

README.md
example/README.md

add pip install

---

src/qfit/qfit.py

changing clash detector to off if there is only a single residue
----
Turning off clash if the structure only has a single residue.

clash detector on/off

---

environment.yml
pyproject.toml
requirements.txt
setup.py
src/qfit/qfit.py

add a symmetry mate clash detector for ligands
----
Add a symmetry mate clash check for ligands. Including this in the clash detector that is applied to the whole generated ensemble blew up runtime, so instead I only apply it to the conformers coming out of MIQP. 
Add symmetry mate-aware clash detection for ligands
----

ligand clash detector qfit.py

---

src/qfit/redistribute_cull_low_occupancies.py

----
This is fixing an issue stemming from redistribute & cull low occupancies where occupancies were not being redistributed correctly leading to issues with refinement and other downstream applications. We have implemented a normalization function & reconfigured the redistribute_occupanies_by_residue around it.

occupancy issues in multiconformer model2

---

src/qfit/qfit.py

quick fix typo: remove version in sidechain

---

src/qfit/qfit_protein.py

- [xx] Will your PR merge into the `dev` branch?  
----
This PR adds ATOM residues with UNK and nucleic acid residues to hetatms. This means that qFit will not try to model the residues but they will be included in the output model with the same coordinates as the input model. 
----

add flag for resn == UNK

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/main.yml

- [x ] Will your PR merge into the `dev` branch?  
----
remove testing from windows

remove windows

---

src/qfit/qfit_density.py

- [ x ] Will your PR merge into the `dev` branch?  
- [ x ] Have you **forked from `dev`**?  
- [ x ] Does your PR title succinctly describe the changes?  
- [ x ] Fill out the template below.
----
qfit_density did not work to generate EM maps. It now does.
qfit_density supports creating EM maps.
----

qfit_density works with EM maps

---

src/qfit/custom_argparsers.py
src/qfit/structure/base_structure.py
src/qfit/structure/mmciffile.py
src/qfit/structure/residue.py
src/qfit/structure/structure.py
tests/test_qfit_model_io.py

----
Heavily updated mmCIF.py to make it work with how qFit Structures expect to be constructed, and integrated into the test_qfit_model_io.py testing. I did uncomment the test 4 for cctbx integration to accomplish this, as it used the test mmCIF file already present. That test now passes when given the appropriate EM flags.
qFit can now read mmCIF files.
----

Enable construction of qFit Structures from mmCIF files

---

scripts/post/calc_OP.py
scripts/post/lig_occ.py

----
adding ligand size and normalization

Quick fix post scripts

---

scripts/post/get_seq.py

----
Updates include:
1) change get_seq.py to include all chains and output in fasta format

update to output all chains

---

scripts/post/qfit_final_refine_xray.sh

Edit final qfit refine for X-ray with updated phenix & solvent

---

src/qfit/redistribute_cull_low_occupancies.py

remove hetatms from being redistributed
