ExcitedStates/qfit-3.0

qfit/qfit.py, qfit/qfit_ppiDesign.py, qfit/solvers.py
QPSolver, QPSolver2 and MIQPSolver, MIQPSolver2 classes present the same interface.
71b4f8d implements a pseudoclass that chooses an appropriate solver given available packages.
Without an installed pair from {CPLEX/cvxopt; osqp/miosqp}, the --help function is still able to run. This closes #27 .
The package will now fall back on an available solver if the requested solver is not available (e.g. through `--miosqp` flag).
=> Automatically select an appropriate QP solver when needed

src/qfit/__init__.py, src/qfit/b_factor.py, src/qfit/logtools.py, src/qfit/qfit.py, src/qfit/qfit_ligand.py, src/qfit/qfit_protein.py, src/qfit/qfit_residue.py, src/qfit/qfit_segment.py, src/qfit/subset_structure_AH.py, tests/test_qfit_ligand.py, tests/test_qfit_protein.py
This PR implements a unified logging infrastructure across the qFit packages.
Logging to the main logfile is now possible from Pool subprocesses, without race conditions.
This PR paves the way for all print() calls to be replaced with logger.debug() calls.
=> Improve logging infrastructure

src/qfit/backbone.py, src/qfit/samplers.py, src/qfit/structure/math.py, src/qfit/structure/residue.py, src/qfit/structure/structure.py
numpy has deprecated the np.matrix class.
The most significant advantage of np.matrix is easy access to matrix multiplication.
As of py3.5, the matmul infix operator (@) has been available to do this with np.ndarrays.
We are getting DeprecationWarnings bubbling up from np.matrix.
This is because we do rotations a lot (and so matrix-multiply by rotation matrices), and because we use matrix operations in the 5D Jacobian calculations.
This PR will eliminate sources of the deprecated np.matrix type in qfit, using the 
It also chases down all locations where matmul was 'implied' through one of the objects being a np.matrix type, and makes this matmul operation explicit.
=> Replace np.matrix with np.ndarray (fixes #46)

src/qfit/b_factor.py, src/qfit/helpers.py, src/qfit/logtools.py, src/qfit/qfit.py, src/qfit/qfit_ligand.py, src/qfit/qfit_ppiDesign.py, src/qfit/qfit_protein.py, src/qfit/subset_structure_AH.py, tests/test_qfit_ligand.py
I've extracted all my typo commits so far and packaged them up into this PR.
There is no change to meaning of the code / to logic-flow in these commits.
This doesn't attempt to go through _all_ qFit files, just the ones that I've touched / intend to work closely with.
The major commit (PEP8ify) hits most of the PEP8 warnings from `pycodestyle --max-line-length=110`. I've set the length of lines to 110 because 79 (the default) is too short to be reasonable.
=> Fix a few typos, shorten lines, move towards PEP8

src/qfit/qfit.py, src/qfit/qfit_protein.py, src/qfit/solvers.py
**Intermediate files**
Output of intermediate files now requires the `--debug` flag for most qfit programs.
Most users don't need the sampled structures (>>10 MB) to be created; they will generally only be interested in the selected structures.
**Logging**
There are no more print() in qfit.py, qfit_protein.py.
Some print() calls still exist in test_qfit_protein.py, where it makes sense to print---this way we can do further debugging if an Assertion fails during testing.
Merge after #57 .
=> Changes to intermediate file output, and more logging

src/qfit/qfit.py, src/qfit/qfit_protein.py
Previously, we did `raise` on errors from subprocesses.
Not a great idea.
Instead now, we use the built-in `traceback` module to format these appropriately for us, and capture them in an error message.
=> Update some logger messages, change how subprocess errors are caught and handled

src/qfit/structure/pdbfile.py
In some situations (e.g. #65 ), PDBs were incorrectly formatted for intermediate structures. This PR helps with this.
Some fields held None. This is no longer the case, instead we hold the default of `dtype()` for the field.
We also alert the user of _all_ errors encountered in reading the PDB file rather than just letting them disappear.
This PR also adds documentation for functions in structure/pdbfile.py .
This commit goes some way to addressing the problems in #65 , though I think I'm still seeing errors caused by missing atoms in an input pdb.
=> Improve pdb parsing

scripts/post_refine_phenix.sh
NQH flips rely on running phenix.reduce.
Sometimes, phenix.reduce crashes when geometry is not ideal (I think this is the reason?)
We should hold off on NQH flips until we're through this round.
=> No NQH flips in first round of refinement

src/qfit/structure/mmCIF.py
py.test was throwing out DeprecationWarnings.
Fix was pretty straightforward.
```
=============================== warnings summary ===============================
/Users/runner/work/qfit-3.0/qfit-3.0/src/qfit/structure/mmCIF.py:852
/Users/runner/work/qfit-3.0/qfit-3.0/src/qfit/structure/mmCIF.py:852: DeprecationWarning: invalid escape sequence \S
"(?:_(.+?)[.](\S+))"               "|"  # _section.subsection
/Users/runner/work/qfit-3.0/qfit-3.0/src/qfit/structure/mmCIF.py:854
/Users/runner/work/qfit-3.0/qfit-3.0/src/qfit/structure/mmCIF.py:854: DeprecationWarning: invalid escape sequence \s
"(?:['\"](.*?)(?:['\"]\s|['\"]$))" "|"  # quoted strings
/Users/runner/work/qfit-3.0/qfit-3.0/src/qfit/structure/mmCIF.py:856
/Users/runner/work/qfit-3.0/qfit-3.0/src/qfit/structure/mmCIF.py:856: …
```
=> Mark raw strings in regex as such to fix DeprecationWarnings

src/qfit/relabel.py
During relabelling, we calculate residue pairwise energies to help decide which labelling is optimal.
Previously, the code would calculate residue pairwise energies if the N-atoms of two residues was within a certain cutoff.
I preserved this behaviour when modifying the section.
However, it seems more consistent to me that we should calculate residue pairwise energies if _any_ atom is within the cutoff radius.
This PR will produce this new behaviour.
I expect results coming from relabel.py will be slightly different.
=> Calc pairwise energy if _at least one atom_ within cutoff

src/qfit/qfit.py, src/qfit/qfit_ligand.py, src/qfit/qfit_protein.py
Previously when running --debug, this created gigabytes of intermediate conformer files (heavily compressible, but still...).
This PR puts this behaviour under --write_intermediate_conformers; --debug now controls just logging messages. and the output of a single structure for all rebuilt residues.
=> Add write_intermediate_conformers option (fixes #78)

src/qfit/volume.py
If MRC file is a 2D stack, its spacegroup==0. qFit will then tell the user to input map not 2D stack.
=> Catch error when MRC files contain 2D stack

src/qfit/qfit.py
np.arange should create a range across [start, stop).
np.arange.__doc__, however, states that there are 'inconsistencies' with non-integer steps.
This refers to floating point (FP) errors: there are fundamental limits to representing real numbers with a finite number of bits.
0.1 is one of those real numbers that _cannot_ be represented precisely in binary FP.
np.arange works by repeated addition, so the magnitude of error will increase with an increasing length of arange.
The fix I am implementing here is to bring _stop_ inwards by N/2 * ε,
where N is the expected length of the array, and
ε is the smallest negative FP such that 1 - ε < 1.
=> Use epsilon to prevent FP errors in calculating backbone amplitude array

README.md
- `--python` doesn't appear to be an option for conda
- Needed to be quoted so zsh (probably bash too?) doesn't treat it as a redirect
=> Fixup python version requirement in README

scripts/post/qfit_final_refine_xray.sh
Currently, there is a non-continuous adp function: inside the loop, we use (whatever is default), and we override it for the final round.
If the structure is < 1.5 Å, this can cause inconsistencies with occupancies. The last round of refinement, an alt-conf can suddenly drop to 0.02 ... without being culled.
Putting the $adp variable in the loop will improve consistency with the last round of refinement.
=> Add adp parameters to iterative refinement loop

README.md, src/qfit/custom_argparsers.py, src/qfit/qfit.py, src/qfit/qfit_ligand.py, src/qfit/qfit_protein.py, src/qfit/qfit_residue.py
----
Fixes #69 .
- Make default values for all command-line options appear in --help
- Improve clarity by making all flags positively worded, removing some short flags
- Change options to use internal hyphenation (no internal underscores) for consistency
- Unified some options across programs
Flags that changed (maintained short form):
* ~~`--build-stepsize`~~ → `--dofs-per-iteration` (`-b`)
* ~~`--stepsize`~~ → `--dihedral-stepsize` (`-s`)
* ~~`--no-waters`~~ → …
=> Improve flags (& --help) of qfit programs

src/qfit/qfit.py, src/qfit/qfit_ligand.py
----
- Add --rmsd-cutoff option to reject new sampled confs that are too close to existing samplings
- Use the value defined on the command line
- Add --rmsd-cutoff option to qFit-ligand
----
=> Add --rmsd-cutoff option to qFit-ligand

.github/workflows/main.yml
This is updating the miniconda set up tools to https://github.com/conda-incubator/setup-miniconda/issues/101. Github updated about 2 days ago (11/18/2020). See: https://github.com/conda-incubator/setup-miniconda/issues/101
----
- Update the setup-miniconda action in the CI yaml: `.github/workflows/main.yaml`
- (dev only) Fixed an issue with failing CI on GitHub
----
=> Update setup-miniconda GitHub Action (repairs failing CI)

scripts/post/b_factor.py
adding CA option in the B-factor script & changing to remove b-factors from H atoms.
----
----
=> Add Ca option in b-factor.py script

scripts/post/alpha_rmsd.py
1. Previous indentation meant we only looped through residues of the last chain.
We now loop through residues for all matching chains.
2. Previously, only the last-calculated chain of rmsd data was stored.
We now store RMSD for all matching chains.
3. Use an f-string filename for readability.
=> Fixup indentation in alpha_rmsd

.github/workflows/main.yml, README.md, environment.yml, pyproject.toml, setup.py, src/qfit/samplers.py, src/qfit/structure/structure.py
----
This bumps the version of python we require to 3.7+.
Python 3.6 is end-of-life at the end of 2021.
On top of this, moving to 3.7 means that we can rely on dataclasses being part of the standard library (which will make future development easier).
- Now require python 3.7+
=> Move to python 3.7, 3.8

src/qfit/volume.py
----
This fix adds a check to make sure the user provides a resolution value if the input map is in MRC/CCP4 or MAP formats. If not provided, raises an error and stops.
- If using a real-space map, the user must provide a resolution value
=> Make sure the user provides a resolution value if the input map is in MRC/CCP4 or MAP formats

src/qfit/__init__.py, src/qfit/qfit.py, src/qfit/qfit_covalent_ligand.py, src/qfit/qfit_ligand.py, src/qfit/qfit_ppiDesign.py, src/qfit/qfit_protein.py, src/qfit/qfit_residue.py, src/qfit/qfit_segment.py, tests/test_qfit_ligand.py, tests/test_qfit_protein.py
----
There were multiple 'option' classes in the src code in qfit.py, qfit_ligand.py, qfit_segment.py, qfit_covalent_ligand.py, qfit_protein.py, qfit_residue.py, init.py as well as the test files for qfit_ligand and qfit_protein that were inheriting from BaseQFitOptions class.
These classes have been merged into a single class called QFitOptions.
- Merged all derived classes into QFitOptions
----
=> Unify all QFitOptions classes into a single class

src/qfit/qfit_protein.py
This fix is related to bug #139. qFit protein was crashing when large maps (only examples were from cryoEM) were fed into the pool multiprocessor due to memory issues.
The fix that was created was to subset the map for every residue before we launch the pool jobs. ~A dictionary is created which has a reduced map attached to the residue.~ This step was previously done within each pool job (ie pool job got entire map, then subsetted and fed into qFit residue).
- qfit_protein …
=> Fixing large maps being able to be fed into qFit Protein without crashing

src/qfit/qfit.py, src/qfit/qfit_protein.py
----
Currently, when options.nproc is 1, qfit_protein launches a multiprocessing.Pool with a single worker. This is a bit much.
With this PR, we no longer bother launching a Pool, and instead just run the residue sampling/scoring in MainProcess.
We will need to watch out for differences in behaviour that might occur between things run with nproc=1 and those with nproc>1. Errors might be masked in either one of these situations.
Where nproc=1, there will be access to the …
=> If options.nproc is 1, run QFitRotamericResidue job in MainProcess

src/qfit/qfit.py, src/qfit/qfit_protein.py
----
Closes #179 .
Make sure that qfit_protein doesn't double up on HETATM residues in the multiconformer_model.pdb output.
Add a bunch of commentary to improve clarity --- so this doesn't happen again.
- Fixed an issue where qfit_protein would duplicate HETATM residues
----
=> 179 qfit protein outputting duplicate hetatms

scripts/post/qfit_final_refine_xray.sh
----
Changed how x-ray data labels are looked for in the mtz dump data in qfit_final_refine_xray.sh. It now includes a more comprehensive list of labels to check and performs comparisons correctly. All parameters for the phenix refinements (including cif files) are now being printed in .params files which can then be directly given as input to phenix.refine. This prevents long if..else blocks in the script. Also prevent crashing of phenix refine due to duplicate R-free flag …
=> Fixed X-ray data labels search and changed how phenix refinement parameters are given in post qfit refinement xray script

src/qfit/custom_argparsers.py, src/qfit/qfit_protein.py
----
When you input a map/model in the incorrect order qFit used to try to run and would crash because it could not read the model appropriately. 
Now qFit checks the file extension for the map and model and if the incorrect file extension exists, then qFit returns error message asking user to check the order of the input map/model.
=> Better error message map/model are in the incorrect order upon input. 

README.md, scripts/post/qfit_final_refine_xray.sh, src/qfit/qfit_protein.py
----
This pull requests make three small changes:
1) only outputs multiconformer_model.pdb if --debug flag is on. This file is not needed and should not be used except for by developers.
2) updates readme/help on qFit protein to not use -z electron as that is currently not workoing
3) add normalize occupancy at beginning of post refine script to patch issue in qFit protein  (not summing occupancies to one).
=> Small patch fixes

src/qfit/qfit.py, src/qfit/qfit_protein.py, src/qfit/qfit_residue.py, src/qfit/structure/ligand.py, src/qfit/structure/residue.py
----
In a QFitProtein job, we throw _all_ rotameric residues onto a queue, and fork PoolWorker jobs to residue sampling.
At the start of these jobs, we check to see if a residue-sampling checkpoint (multiconformer_residue.pdb) exists.
The issue with this approach is that the map around the residue has to be extracted, pickled, sent to the PoolWorker, unpickled before we check whether this residue has been already sampled. If it has, we do ~1.5s worth of work for nothing! …
=> If a residue-sampling checkpoint exists, don't add it to the list of residues to be sampled

src/qfit/qfit_protein.py, src/qfit/volume.py
----
XMap.extract creates a copy of the map (around target coords).
This is used for:
- subsetting the density map to just the portion around the residue-of-interest (as in QFitProtein)
- expanding the map to include a buffer around the protein-of-interest (as in QFitSegment)
Before this PR, it creates this new map-copy by iterating voxel-by-voxel through the map.
This is terribly inefficient, and on an ordinary-size, average-resolution map, takes about 120 s to iterate …
=> Rewrite XMap.extract() for 500x speed boost

src/qfit/qfit.py, src/qfit/solvers.py, src/qfit/structure/__init__.py, src/qfit/structure/structure.py
----
This will close #52.
This will also make #199 redundant.
This takes Steph's function from #199 for removing the lowest-occupancy conformer from the closest conformer pair.
I then flatten the code:
- move calc_RMSD to the structure module
- use the _indexes_ of selected conformers, rather than match on their values
I also make the debug messages more informative, though I currently have to wait on the convenience property "shortcode" added in PR #211 .
- Added conformer …
=> Fix non-convex objective errors by selectively deleting conformers

src/qfit/qfit_residue.py
This adds in custom argparse commands to make sure that the map and model are in the correct order in qFit_residue. If they are not in the correct order, an error message stating this is outputted.
=> Improved error message: unknown file type error in qfit residue

example/3K0N_refine.pdb, tests/test_qfit_protein.py
This PR is updating the PDB 3K0N that is run for the tests. Due to some slight mis-modeling of M61, it was causing F113 to crash into it. We will now be using a re-refined 3K0N PDB that models M61 along with a few other residues better into the density. 
-
=> adding re-refined 3K0N for tests

src/qfit/structure/structure.py
=> tab error in normalize occ

scripts/post/qfit_final_refine_xray.sh
=> move where we add hydrogens to after while loop

src/qfit/qfit.py, src/qfit/qfit_protein.py
=> Add in B-factor sampling

src/qfit/qfit.py, src/qfit/qfit_protein.py
=> adding flag to only run qFit segment

scripts/post/qfit_final_refine_xray.sh
This will be implemented in the last refinement round
----
This change will add ordered solvent in the last round of refinement. This will 'Add (or/and remove) and refine ordered solvent molecules (water)'. This will help with clashing water molecules and significantly improved Rfree for every model compared to our previous refinement script.
=> adding order solvent picking in refinement

scripts/post/qfit_final_refine_xray.sh, src/qfit/qfit_protein.py
----
This change will create a grouped occupancy file based on residues that are grouped with qFit segment. 
It breaks grouped occupancy when the CA has one conformation. 
The occupancy parameter file is then used during the iterative refinement. It is not kept for final refinement. 
The normalize occupancy script needs to be updated to reflect this grouped refinement and remove grouped residues with occupancies that fall below 0.1 (or something like that based on …
=> 301 re create refinement script to group occupancy of segment alt locs

scripts/post/qfit_final_refine_xray.sh, scripts/post/qfit_segment_refine.sh, src/qfit/qfit.py, src/qfit/qfit_protein.py, src/qfit/structure/structure.py
=> 301 reconfigure qfit segment

src/qfit/create_rot_lib.py
=> create all rotamers script

README.md, src/qfit/qfit.py, src/qfit/qfit_protein.py
----
This is implementing qscore (https://github.com/gregdp/mapq, https://www.nature.com/articles/s41592-020-0731-1) for EM structures. This implements an option to provide a qscore txt file and qFit will not model residues with sidechain qscores <0.7 as these residues do not have enough supporting density.
=> qscore cutoff option for EM structures

src/qfit/qfit.py
----
In a discussion with coauthors in 2023-Apr, the sample_b() routine should _expand_ the number of conformers going into the MIQP round --- each conformer turns into 5 conformers with differing B-factors.
- Fixed an issue where B-factor sampling reduced the number of conformers.
----
=> Correct sample_b() implementation

src/qfit/qfit_protein.py
----
QFitSegment was using a custom 'padding' during map extraction.
This commit changes the map extraction in QFitSegment to use the same routine as is being used in QFitRotamericResidue (and elsewhere).
We currently ask the user what padding they'd like for map calculations: we should respect that.
- Respect --padding during QFitSegment
----
=> Unify map extraction: use --padding option (and default value) in QFitSegment

src/qfit/qfit.py
We have been looking at the entire segment (often the entire chain or protein) for missing backbone atoms. If there are any missing backbones, all backbone sampling for that residue is abandoned. We should only check if the backbone exists within the segment used for the inverse kinematic algorithm (residue - 3 or residue +3).
----
----
=> updating missing backbones

src/qfit/qfit.py, src/qfit/qfit_ligand.py, src/qfit/solvers.py, tests/test_qfit_protein.py
----
We were previously selecting the number of conformers from the _last_ iteration of the BIC loop, because a "else break" had been commented and removed.
As such, every MIQP was performed 5 times (redundantly!), and the last MIQP iteration was the one that made it through (threshold/tdmin = 0.2).
This PR implements the desired behaviour. It calculates the MIQP solutions for all thresholds, and then chooses the solution with lowest BIC.
The number of conformers selected is …
=> Make BIC routine _actually_ select based on lowest BIC

src/qfit/qfit.py
----
This PR is changing the BIC penalty parameter from natoms * 4* nconfs to nconfs in only segments. Including all the atoms and the parameters sampled reduce our ability to identify alt confs in the segment portion of the algorithm.
=> Segment BIC criteria = nconfs

src/qfit/solvers.py
----
When CPLEX is not installed, we used to get the error message:
`ImportError: cannot import name 'SolverError' from 'qfit.solvers' `
But we should be returning a runtime error stating that CPLEX and CVOPT are not installed.
=> Improved Error Message when CPLEX is not installed

src/qfit/qfit.py
This option determines if we sample a single chi angle at a time or 2 chi angles at a time. 
Unknown why this was set to 2. It was done by Gydo. But based on the extensive sampling with other things, we can reduce it to 1. 
After running this through the qFit test set compared to chi_sampling_dof = 2, this gave equal results in the number of altconfs and Rfree values. Examining the <100 residues that had differences, they were minor (RMSD < 0.07). But this significantly reduces our sampling. 
*Explain to a new user by completing the sentence: …
=> updating chi sampling dof per iteration to 1

src/qfit/qfit.py, src/qfit/samplers.py
----
Link to issue:
https://github.com/ExcitedStates/qfit-3.0/issues/354
Currently we only sample up/down some input angle for aromatic side chains. I'm adding to this sampling method, letting the side chains rotate closer to 360 degrees rather than just about a single axis. This covers more of the conformational space.
Modified α-β-γ angle sampling in qfit_protein to cover more of the conformational space. 
----
=> 354 re work angle sampling to rotate 360

environment.yml, setup.py, src/qfit/qfit.py, src/qfit/qfit_covalent_ligand.py, src/qfit/qfit_ligand.py, src/qfit/qfit_protein.py, src/qfit/qfit_residue.py, src/qfit/solvers.py, src/qfit/utils/optional_lazy_import.py, tests/test_qfit_ligand.py, tests/test_solvers.py
----
Fixes #361 .
- Reimplemented open-source solvers (osqp, miosqp)
- Only the installed solvers will be listed in `qfit_protein --help`
- The user can override the default-selected solver (e.g `--qp-solver=CVXOPTSolver --miqp-solver=MIOSQPSolver`)
- (dev) Refactored solvers.py
----
=> Re-implement open source solvers

src/qfit/qfit.py, src/qfit/qfit_protein.py
----
This PR will update the hyperparameter from 0.95 to 1.5 within the BIC equation in qFit. 0.95 was chosen originally. After testing 1.5 had the best result between choosing the least number of conformations and not reducing Rfree.
=> Updating BIC hyperparameter

src/qfit/qfit.py
If too many conformers are generated during sidechain, split conformer array into two sections and score them separately
----
If too many conformers are generated during sample_sidechain(), split conformer array into two sections and score them separately. Concatenate after scoring both sections. This allows us to sample >15000 conformers without overloading QP. 
This is a temporary fix. Ideally, we want to reduce sampling as the time sampling is getting increasingly high …
=> Split QP step into two in sample sidechain

src/qfit/qfit.py, src/qfit/qfit_protein.py
----
If the input PDB has altlocs for C, CA, N, or O, it will run qFit residue starting from both conformations. This specifically will run sample_backbone x number of times determined by the number of backbone coordinates. This will then feed in both samplings into the coor_set for subsequent sampling. 
This is done by creating a dictionary in qfit_protein with the coordinates for all altlocs and the anisotropic matrix if applicable. 
This is still suffering from …
=> Allow qFit to run with multiple backbone inputs

README.md
- [] Will your PR merge into the `dev` branch?  
----
----
=> update for CVXPY citation

src/qfit/qfit.py
If qFit does not generate any conformers due to clashes, we will use the deposited conformer.
----
If qFit does not produce any conformers due to clashes, this used to result in conformer being returned. This was an issue for segment and refinement (& the model). Now it just returns the deposited conformer.
=> Use deposited conformers if clashes

src/qfit/structure/base_structure.py, src/qfit/utils/mock_utils.py, src/qfit/xtal/transformer.py, src/qfit/xtal/volume.py, tests/test_qfit_protein_synth.py, tests/unit/test_xtal_volume.py
The transformer will now use the P1 unit cell defined by the map if the structure does not explicitly specify symmetry.  This change also tests the placeholder symmetry used by the PDB in CRYST1 records.
=> Fix Cryo-EM input without symmetry

README.md, src/qfit/qfit.py
=> remove duplicate rotamer sampling

scripts/post/qfit_final_refine_xray.sh
create_restraint file needs to be updated when changing occupancies
----
Not re-creating restraint file during loop is causing issues with occupancy iterative refinement loop. This change now incorporates this script within the loop rather than before the loop.
=> Restraint creation file in loop

environment.yml, pyproject.toml, setup.py, src/qfit/qfit.py
----
There are two changes this PR is making:
1) It is eliminating us running through MIQP 5 times in the non-BIC scenario. We still use all 5 thresholds for MIQP, but then always save the last one (threshold =0.2). This changes MIQP to only use the 0.2 threshold UNLESS BIC is turned on. This should speed up the algorithm significantly.
2) This turns off BIC selection during intermediate (non-terminal) steps of side chains. While we want to eliminate options for subsequent …
=> remove BIC from side chain sampling

src/qfit/structure/mmciffile.py
----
Bugfix as mmciffile.py write used os, and it was not imported. Additionally, the writer was trying to use a non-existent attribute in unit_cell, my mistake as I got confused about cryst info vs unit_cell.
mmciffile.py writer fixes
----
=> missing import os breaks write in mmciffile.py

scripts/post/qfit_final_refine_ligand.sh, src/qfit/structure/structure.py
Yes
Yes
Yes
----
https://github.com/ExcitedStates/qfit-3.0/issues/517
Structure.split_models() calls a module that is not imported. This PR adds that import
Fixes a bug that causes a fatal error in structure.split_models()
----
=> Add import iotbx.pdb.hierarchy to structure.py
